# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master


steps:
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      cd /home/vsts/work/1/s
      touch file.txt
      echo Hello world
      

- task: SendEmail@1
  inputs:
    To: 'proamritgupta@gmail.com'
    From: 't_amrit.gupta@tatadigital.com'
    Subject: 'check'
    Body: 'check'
    BodyAsHtml: false
    AddAttachment: false
    SmtpServer: 'smtp.sendgrid.net'
    SmtpUsername: 'azure_2adfbb4338ada7a9e01fa67080578b9f@azure.com'
    SmtpPassword: 'tcs@12345'

- task: SendGrid@1
  inputs:
    sendgridkey: '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'
    to: 'proamritgutpa@gmail.com'
    from: 'proamritgutpa@gmail.com'
    subject: 'file'
    htmlbody: 'check'
    addattachment: true
    attachment: '/home/vsts/work/1/s/file.txt'